#!/usr/bin/env bash

# Put server name in a relative file appservername
if [ -f appservername ]; then
    SERVER=$(<appservername)
fi

H=$(sed -e 's#.*\-h=\([^[:space:]]*\?\).*#\1#' <<< "$*")
S=$(sed -e 's#.*\-s=\([^[:space:]]*\?\).*#\1#' <<< "$*")

if [ "$H" == "-h" ]; then
    printf "Use -s to specify name of server in pm2, eg. -s=myapp-server\n"
    exit 1;
fi

# Check that either -s or server (appservername) are set
if [ "$S" == "$*" ] && [ "$SERVER" == "" ]; then
    printf "You must specify which nuxt server to use - eg. -s=someserver\n"
    exit 1
else
    # Set server, whether using the appservername or -s
    if [ "$S" == "$*" ]; then
        SERVER=${SERVER}
    else
        SERVER=$S
    fi
fi

CMD="pm2 reload $SERVER"

eval $cmd

