#!/usr/bin/env bash

# Put server name in a relative file appservername
if [ -f appservername ]; then
    SERVER=$(<appservername)
fi

H=$(sed -e 's#.*\-h=\([^[:space:]]*\?\).*#\1#' <<< "$*")
S=$(sed -e 's#.*\-s=\([^[:space:]]*\?\).*#\1#' <<< "$*")
N=$(sed -e 's#.*\-n=\([^[:space:]]*\?\).*#\1#' <<< "$*")

if [ "$H" == "-h" ]; then
    printf "Use -s to specify name of server in pm2, eg. -s=myapp-server\n"
    printf "Use -n to specify path of node_modules, eg. -n=../current/app\n"
    exit 1;
fi

# Check that either -s or server (appservername) are set
if [ "$S" == "$*" ] && [ "$SERVER" == "" ]; then
    printf "You must specify which nuxt server to use - eg. -s=someserver\n"
    exit 1
else
    # Set server, whether using the appservername or -s
    if [ "$S" == "$*" ]; then
        SERVER=${SERVER}
    else
        SERVER=$S
    fi
fi

if [ "$N" == "$1" ]; then
    printf "You must specify the path to the folder where node-modules live - eg. -n=../current/app\n"
    exit 1
else
    PATH_TO_NODE_FOLDER=$N
fi

CMD="cd $PATH_TO_NODE_FOLDER"
eval $CMD

CMD="pm2 restart ./node_modules/nuxt/bin/nuxt-start --name $SERVER"

eval $CMD

