#!/usr/bin/env bash

while getopts ":h" option; do
    case $option in
      h) echo "Use -s for server name, -a for action name. actions: start, reload, restart, stop, delete, logs, info"; exit ;;
    esac
done

S=$(sed -e 's#.*\-v=\(.*\).*#\1#' <<< "$1$2")
A=$(sed -e 's#.*\-a=\(.*\).*#\1#' <<< "$1$2")

if [ "$S" == "$1$2" ]; then
    printf "You must specify which nuxt server to use - eg. -s=someserver\n"
    exit 1
else
    SERVER=$S
fi

if [ "$A" == "$1$2" ]; then
    printf "You must specify which nuxt action to use - eg. -a=reload\n"
    exit 1
else
    ACTION=$A
fi

if [ "$ACTION" == 'start' ] || [ "$ACTION" == 'restart' ]; then

    read -p "Path to node folder? eg. /var/www/app: " PATH_TO_NODE_FOLDER

    CMD="cd $PATH_TO_NODE_FOLDER"
    eval $CMD

    CMD="pm2 $ACTION ./node_modules/nuxt/bin/nuxt-start --name $server"

else
    CMD="pm2 $action $server"
fi

eval $CMD

