#!/usr/bin/env bash

while getopts ":h" option; do
    case $option in
      h) echo "Use -s for server name for the process"; exit ;;
    esac
done

S=$(sed -e 's#.*\-v=\(.*\).*#\1#' <<< "$1")

if [ "$S" == "$1" ]; then
    printf "You must specify which nuxt server to use - eg. -s=someserver\n"
    exit 1
else
    SERVER=$S
fi

CMD="pm2 reload $server"

eval $cmd

