#!/usr/bin/env bash

# Put server name in a relative file appservername
if [ -f appservername ]; then
    SERVER=$(<appservername)
fi

H=$(sed -e 's#.*\-h=\([^[:space:]]*\?\).*#\1#' <<< "$*")
S=$(sed -e 's#.*\-s=\([^[:space:]]*\?\).*#\1#' <<< "$*")
A=$(sed -e 's#.*\-a=\([^[:space:]]*\?\).*#\1#' <<< "$*")

if [ "$H" == "-h" ]; then
    printf "Use -s to specify name of server in pm2, eg. -s=myapp-server\n"
    printf "Use -a for action name. actions: start, reload, restart, stop, delete, logs, info\n"
    exit 1;
fi

# Check that either -s or server (appservername) are set
if [ "$S" == "$*" ] && [ "$SERVER" == "" ]; then
    printf "You must specify which nuxt server to use - eg. -s=someserver\n"
    exit 1
else
    # Set server, whether using the appservername or -s
    if [ "$S" == "$*" ]; then
        SERVER=${SERVER}
    else
        SERVER=$S
    fi
fi

if [ "$A" == "$*" ]; then
    printf "You must specify which nuxt action to use - eg. -a=reload\n"
    exit 1
else
    ACTION=$A
fi

if [ "$ACTION" == 'start' ] || [ "$ACTION" == 'restart' ]; then

    read -p "Path to node folder? eg. /var/www/app: " PATH_TO_NODE_FOLDER

    CMD="cd $PATH_TO_NODE_FOLDER"
    eval $CMD

    CMD="pm2 $ACTION ./node_modules/nuxt/bin/nuxt-start --name $server"

else
    CMD="pm2 $action $server"
fi

eval $CMD

