name: Deploy via AWS SSM

on:
  push:
    branches:
      - dev

jobs:
  deploy-dev:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    # Install AWS CLI v2
    - name: Install AWS CLI
      run: |
        curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
        unzip awscliv2.zip
        sudo ./aws/install
        curl "https://s3.amazonaws.com/session-manager-downloads/plugin/latest/ubuntu_64bit/session-manager-plugin.deb" -o "session-manager-plugin.deb"
        sudo dpkg -i session-manager-plugin.deb

    # Setup AWS CLI
    - name: Set up AWS CLI
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.DEV_AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.DEV_AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.DEV_AWS_REGION }}

    # Send command via AWS SSM
    - name: Execute Command on Instance
      id: ssm
      run: |
        REF_NAME=$(basename ${{ github.event.ref }})

        if [ "${{ github.event_name }}" == "push" ]; then
            COMMAND="./deploy.sh --repo ${{ github.repository }} --branch $REF_NAME"
        elif [ "${{ github.event_name }}" == "release" ]; then
            COMMAND="./deploy.sh --repo ${{ github.repository }} --tag $REF_NAME"
        fi

        # wrap COMMAND so that ubuntu can run it. We are root
        RUN_AS_COMMAND="sudo -u ${{ secrets.DEV_INSTANCE_USER}} -i bash -c \"$COMMAND\""
        # escape double quotes
        RUN_AS_COMMAND=${RUN_AS_COMMAND//\"/\\\"}
        echo "Executing command: $RUN_AS_COMMAND"

        command_id=$(aws ssm send-command \
            --document-name 'AWS-RunShellScript' \
            --parameters "{\"commands\": [\"$RUN_AS_COMMAND\"]}" \
            --instance-ids "${{ secrets.DEV_INSTANCE_ID }}" \
            --output text \
            --query Command.CommandId)

        # Wait for command to finish - but ignore errors
        set +e
        aws ssm wait command-executed \
            --command-id "${command_id}" \
            --instance-id "${{ secrets.DEV_INSTANCE_ID }}"
        # return to normal error handling
        set -e

        # Check exit code
        exit_code=$(aws ssm list-command-invocations \
            --command-id "${command_id}" \
            --instance-id "${{ secrets.DEV_INSTANCE_ID }}" \
            --query "CommandInvocations[].StatusDetails" \
            --output text)

        # Get output
        aws ssm get-command-invocation \
            --command-id "${command_id}" \
            --instance-id "${{ secrets.DEV_INSTANCE_ID }}" \
            --query "StandardOutputContent" \
            --output text \
            --no-cli-pager

        # Printf the command link to be helpful
        echo "Command link: https://console.aws.amazon.com/systems-manager/run-command/${{ secrets.DEV_AWS_REGION }}/${{ secrets.DEV_INSTANCE_ID }}/details/${command_id}"

        # Now report on exit code and exit properly.
        if [ "$exit_code" = "Success" ]; then
            echo "✅ Deploy Command succeeded"
        else
            echo "❌ Deploy Command failed"
            # Get error output & don't wait for input
            aws ssm get-command-invocation \
                --command-id "${command_id}" \
                --instance-id "${{ secrets.DEV_INSTANCE_ID }}" \
                --query "StandardErrorContent" \
                --output text \
                --no-cli-pager
            exit 1
        fi
