name: Deploy to Server

on:
  push:
    branches:
      - main
      - dev
  release:
    types:
      - published

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup knownhosts
      env:
        SERVER_KEYSCAN: ${{ secrets.SERVER_KEYSCAN }}
      run: |
        mkdir -p ~/.ssh
        echo "$SERVER_KEYSCAN" >> ~/.ssh/known_hosts
        cat ~/.ssh/known_hosts

    - name: Deploy to server
      env:
        SERVER_SSH_KEY: ${{ secrets.SERVER_SSH_KEY }}
        SERVER_ADDRESS: ${{ secrets.SERVER_ADDRESS }}
        SERVER_KEYSCAN: ${{ secrets.SERVER_KEYSCAN }}
        DEPLOY_USER: ${{ secrets.DEPLOY_USER }}
      run: |
        echo "$SERVER_SSH_KEY" > private_key
        chmod 600 private_key

        REF_NAME=$(basename ${{ github.event.ref }})

        if [ "${{ github.event_name }}" == "push" ]; then
            ssh -i private_key $DEPLOY_USER@$SERVER_ADDRESS "./deploy.sh --repo ${{ github.repository }} --branch $REF_NAME"
        elif [ "${{ github.event_name }}" == "release" ]; then
            ssh -i private_key $DEPLOY_USER@$SERVER_ADDRESS "./deploy.sh --repo ${{ github.repository }} --tag $REF_NAME"
        fi

        rm -f private_key
