name: Deploy Dev via AWS SSM

on:
  push:
    branches:
      - dev

jobs:
  deploy-dev:
    uses: ./.github/workflows/deploy-aws-ssm.yml
    with:
      AWS_REGION: ${{ vars.DEV_AWS_REGION }}
      INSTANCE_ID: ${{ vars.DEV_INSTANCE_ID }}
      INSTANCE_USER: ${{ vars.DEV_INSTANCE_USER }}
      GITHUB_DEPLOYMENT_ENV_NAME: development
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.DEV_AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.DEV_AWS_SECRET_ACCESS_KEY }}

