name: Deploy Prod via AWS SSM

on:
  release:
    types:
      - published

jobs:
  deploy-prod:
    uses: ./.github/workflows/deploy-aws-ssm.yml
    with:
      AWS_REGION: ${{ vars.PROD_AWS_REGION }}
      INSTANCE_ID: ${{ vars.PROD_INSTANCE_ID }}
      INSTANCE_USER: ${{ vars.PROD_INSTANCE_USER }}
      GITHUB_DEPLOYMENT_ENV_NAME: production
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.PROD_AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.PROD_AWS_SECRET_ACCESS_KEY }}